### ISSUE TITLE
LowessError: {'LowessError': 'x or y is not a Pandas series.'}

### ISSUE THREAD

**Issue by ftk1000** [arokem/lowess#3]
The following code 

        import lowess as lo
        import numpy as np

        # For the 1D case:
        x = np.random.randn(100)
        f = np.cos(x) + 0.2 * np.random.randn(100)
        x0 = np.linspace(-1,1,10)
        f_hat = lo.lowess(x, f, x0)
        import matplotlib.pyplot as plt
        fig,ax = plt.subplots(1)
        ax.scatter(x,f)
        ax.plot(x0,f_hat,'ro')
        plt.show()

returns this error:

LowessError                               Traceback (most recent call last)
<ipython-input-4-c20b02532136> in <module>
      6 f = np.cos(x) + 0.2 * np.random.randn(100)
      7 x0 = np.linspace(-1,1,10)
----> 8 f_hat = lo.lowess(x, f, x0)
      9 import matplotlib.pyplot as plt
     10 fig,ax = plt.subplots(1)

~\Anaconda3\lib\site-packages\lowess\lowess.py in lowess(x, y, bandwidth, polynomialDegree)
     52 
     53     # Validate the inputs
---> 54     validateInput(x, y, bandwidth, polynomialDegree)
     55 
     56     # Initialise a Pandas Series for the results.

~\Anaconda3\lib\site-packages\lowess\lowess.py in validateInput(x, y, bandwidth, polynomialDegree)
     97         # Check that it is a Pandas Series.
     98         if not isinstance(s, pd.core.series.Series):
---> 99             raise LowessError('x or y is not a Pandas series.')
    100 
    101         # Check that it is numeric

LowessError: {'LowessError': 'x or y is not a Pandas series.'}

**Comment by arokem** [comment]
Sorry for the confusion. I think you are running another software package with the same name: (https://github.com/CCGE-Cambridge/lowess).
